export const CONTENT_PATH='content/portfolio.json';
export const DRAFT_KEY='rezazdl-content-v1';
export const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function youtubeId(value){try{const u=new URL(value);if(u.protocol!=='https:')return null;const host=u.hostname.toLowerCase().replace(/^www\./,'');let id;if(host==='youtu.be')id=u.pathname.slice(1).split('/')[0];else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:embed|shorts|live)\/([^/]+)/)?.[1];return /^[\w-]{11}$/.test(id||'')?id:null}catch{return null}}
export function safeAsset(value,kind='image'){if(typeof value!=='string')return '';if(kind==='image'&&/^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(value))return value;if(kind==='video'&&/^data:video\/mp4;base64,[A-Za-z0-9+/=]+$/.test(value))return value;if(/^assets\/[A-Za-z0-9_./-]+$/.test(value)&&!value.includes('..'))return value;try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href}catch{}return ''}
export function assetURL(value,kind='image'){const safe=safeAsset(value,kind);return safe?new URL(safe,document.baseURI).href:''}
export function httpsURL(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
const str=(v,max=60000)=>String(v??'').slice(0,max);
export function normalizeContent(raw){
 if(!raw||raw.version!==1||!Array.isArray(raw.collections))throw Error('ساختار فایل محتوا معتبر نیست.');
 const ids=['video','3d','interactive'];if(raw.collections.length!==3||ids.some(id=>!raw.collections.some(c=>c.id===id)))throw Error('هر سه دستهٔ اصلی باید در فایل وجود داشته باشند.');
 const seen=new Set();
 return {version:1,settings:{heroVideo:safeAsset(raw.settings?.heroVideo??'','video'),analytics:{enabled:raw.settings?.analytics?.enabled===true,scriptUrl:httpsURL(raw.settings?.analytics?.scriptUrl||'https://cloud.umami.is/script.js'),websiteId:str(raw.settings?.analytics?.websiteId,100)}},collections:raw.collections.map(c=>({id:c.id,title:str(c.title,160),description:str(c.description,1000),image:safeAsset(c.image),projects:(Array.isArray(c.projects)?c.projects:[]).slice(0,300).map(p=>{
 const id=str(p.id,100);if(!/^[a-zA-Z0-9_-]+$/.test(id)||seen.has(id))throw Error('شناسهٔ پروژه نامعتبر یا تکراری است.');seen.add(id);
 return {id,title:str(p.title,200),subtitle:str(p.subtitle,2000),kind:str(p.kind,200),published:p.published!==false,cover:safeAsset(p.cover),media:(Array.isArray(p.media)?p.media:[]).slice(0,100).map(m=>({type:m.type==='youtube'?'youtube':'image',src:m.type==='youtube'?(youtubeId(m.src)?str(m.src,2000):''):safeAsset(m.src),caption:str(m.caption,1000),alt:str(m.alt,1000)})),facts:(Array.isArray(p.facts)?p.facts:[]).slice(0,30).map(f=>({label:str(f.label,200),value:str(f.value,2000)})),sections:(Array.isArray(p.sections)?p.sections:[]).slice(0,100).map(s=>({heading:str(s.heading,300),body:str(s.body)}))};})}))};
}
export async function loadPublished(){const r=await fetch(new URL(CONTENT_PATH,document.baseURI),{cache:'no-cache'});if(!r.ok)throw Error('دریافت محتوا ممکن نشد. دوباره تلاش کنید.');return normalizeContent(await r.json())}
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DRAFT_KEY,1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function readDraft(){const db=await database();return new Promise((resolve,reject)=>{const t=db.transaction('drafts'),r=t.objectStore('drafts').get('current');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()})}
export async function saveDraft(data){const db=await database();return new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite');t.objectStore('drafts').put(data,'current');t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>{db.close();reject(t.error)};t.onabort=()=>reject(t.error)})}
export async function clearDraft(){const db=await database();return new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite');t.objectStore('drafts').delete('current');t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>reject(t.error)})}
// A small, deliberately HTML-free Markdown renderer for editable project text.
function inline(raw){let out=escapeHTML(raw);out=out.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,(_,label,url)=>{const decoded=url.replace(/&amp;/g,'&');try{const u=new URL(decoded);if(!['http:','https:'].includes(u.protocol))return label;return `<a href="${escapeHTML(u.href)}" target="_blank" rel="noopener noreferrer">${label}</a>`}catch{return label}});return out.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>')}
export function renderText(text){const blocks=String(text||'').replace(/\r\n/g,'\n').split(/\n\s*\n/);return blocks.filter(Boolean).map(block=>{const lines=block.split('\n');if(lines.every(l=>/^[-*] /.test(l)))return '<ul>'+lines.map(l=>'<li>'+inline(l.slice(2))+'</li>').join('')+'</ul>';if(lines.every(l=>/^\d+\. /.test(l)))return '<ol>'+lines.map(l=>'<li>'+inline(l.replace(/^\d+\. /,''))+'</li>').join('')+'</ol>';if(lines.every(l=>/^> /.test(l)))return '<blockquote>'+lines.map(l=>inline(l.slice(2))).join('<br>')+'</blockquote>';return lines.map((line,i)=>{const h=line.match(/^#{1,4}\s+(.+)/);return h?`<h4>${inline(h[1])}</h4>`:`${i&& !/^#/.test(lines[i-1])?'<br>':''}${inline(line)}`}).join('')}).map(block=>/^<(ul|ol|blockquote|h4)/.test(block)?block:`<p>${block}</p>`).join('')}
