import {normalizeContent} from '../content-model.js?v=20260923-home2';
const encodePath=value=>value.split('/').map(encodeURIComponent).join('/');
function repoConfig(config){const match=config.repo.trim().replace(/^https:\/\/github.com\//,'').replace(/\.git$/,'').replace(/\/$/,'').match(/^([\w.-]+)\/([\w.-]+)$/);if(!match)throw Error('آدرس مخزن باید به شکل username/repository باشد.');const root=config.root.trim().replace(/^\/+|\/+$/g,'');if(root&&!/^[\w-]+(?:\/[\w-]+)*$/.test(root))throw Error('نام پوشهٔ سایت معتبر نیست.');if(!config.branch.trim()||/[\s~^:?*\[\\]|\.\./.test(config.branch))throw Error('نام شاخه معتبر نیست.');if(!config.token.trim())throw Error('توکن GitHub را وارد کنید.');return {repo:match[1]+'/'+match[2],branch:config.branch.trim(),root,token:config.token.trim()}}
export function githubClient(config){const c=repoConfig(config);const base=`https://api.github.com/repos/${c.repo}`;async function api(path,method='GET',body){const response=await fetch(base+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){if(response.status===401)throw Error('توکن معتبر نیست یا منقضی شده است.');if(response.status===403)throw Error('دسترسی کافی نیست یا محدودیت GitHub فعال شده است. دسترسی Contents را بررسی کنید.');if(response.status===404)throw Error('مخزن، شاخه یا فایل محتوا پیدا نشد. ابتدا بستهٔ سایت را آپلود کنید.');if(response.status===409||response.status===422)throw Error('نسخهٔ مخزن تغییر کرده یا شاخه محافظت‌شده است؛ چیزی بازنویسی نشد. محتوا را دوباره دریافت کنید.');throw Error(`خطای ارتباط با GitHub (${response.status}). دوباره تلاش کنید.`)}return response.status===204?null:response.json()}
 const path=(c.root?c.root+'/':'')+'content/portfolio.json';
 return {config:c,api,path,async head(){return (await api('/git/ref/heads/'+encodePath(c.branch))).object.sha},async read(){const head=await this.head();let blob=await api('/contents/'+encodePath(path)+'?ref='+encodeURIComponent(head));if(!blob.content)blob=await api('/git/blobs/'+blob.sha);const bytes=Uint8Array.from(atob(blob.content.replace(/\s/g,'')),ch=>ch.charCodeAt(0));return {head,content:normalizeContent(JSON.parse(new TextDecoder().decode(bytes)))}},async publish(content,expectedHead,onProgress=()=>{}){
  if(await this.head()!==expectedHead)throw Error('شخص یا مرورگر دیگری مخزن را تغییر داده است. پیش‌نویس شما محفوظ است؛ ابتدا نسخهٔ پشتیبان بگیرید و نسخهٔ تازه را دریافت کنید.');
  const doc=normalizeContent(content),uploads=[],known=new Map(),prefix=c.root?c.root+'/':'';
  async function upload(src){if(!src.startsWith('data:'))return src;if(known.has(src))return known.get(src);const match=src.match(/^data:(image\/(png|jpeg|webp|gif)|video\/(mp4));base64,(.+)$/);if(!match)throw Error('فایل آپلودشده معتبر نیست.');const bytes=Uint8Array.from(atob(match[4]),ch=>ch.charCodeAt(0));const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');const ext=match[2]||match[3],path=`assets/uploads/${digest.slice(0,24)}.${ext}`;onProgress('در حال ارسال فایل‌های جدید…');const blob=await api('/git/blobs','POST',{content:match[4],encoding:'base64'});uploads.push({path:prefix+path,mode:'100644',type:'blob',sha:blob.sha});known.set(src,path);return path}
  doc.settings.heroVideo=await upload(doc.settings.heroVideo);
  doc.home.aboutPhoto=await upload(doc.home.aboutPhoto);
  for(const section of doc.home.extraSections)section.image=await upload(section.image);
  for(const collection of doc.collections){collection.image=await upload(collection.image);for(const p of collection.projects){p.cover=await upload(p.cover);for(const m of p.media)if(m.type==='image')m.src=await upload(m.src)}}
  onProgress('در حال ذخیرهٔ محتوا…');const commit=await api('/git/commits/'+expectedHead);const tree=await api('/git/trees','POST',{base_tree:commit.tree.sha,tree:[...uploads,{path,mode:'100644',type:'blob',content:JSON.stringify(doc,null,2)+'\n'}]});const next=await api('/git/commits','POST',{message:'Update portfolio content from Rezazdl Studio',tree:tree.sha,parents:[expectedHead]});
  // An atomic, non-forced ref update rejects edits made while uploads were in flight.
  await api('/git/refs/heads/'+encodePath(c.branch),'PATCH',{sha:next.sha,force:false});return {content:doc,head:next.sha,commitURL:`https://github.com/${c.repo}/commit/${next.sha}`};
 }};
}

